// ui/src/lib/Usage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import RefreshCw from "lucide-svelte/icons/refresh-cw";
  import * as api from "./api";
  import { displayError, parseInvokeError } from "./error";
  import UsageChart from "./UsageChart.svelte";
  import { foldUsage, providerLabel } from "./usageMerge";
  import {
    formatCount,
    formatDayShort,
    formatPercent,
    formatTokens,
    formatUsd,
    makeWindow,
  } from "./usageFormat";
  import type { UsageMetric, UsageSummary } from "./usageTypes";

  const WINDOWS = [
    { days: 1, label: "Past 24h" },
    { days: 7, label: "7 days" },
    { days: 30, label: "30 days" },
    { days: 90, label: "90 days" },
  ] as const;

  let summary = $state<UsageSummary | null>(null);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let windowDays = $state(30);
  let metric = $state<UsageMetric>("cost");
  let activeWindow = $state(makeWindow(30));
  let loadGen = 0;

  const folded = $derived(foldUsage(summary));
  const headline = $derived(metric === "cost" ? formatUsd(folded.costUsd) : formatTokens(folded.totalTokens));
  const recent = $derived(
    (windowDays === 1 ? folded.hourly : folded.daily).toReversed().slice(0, 8),
  );
  const models = $derived(
    [...folded.models].sort((a, b) =>
      metric === "cost" ? b.costUsd - a.costUsd : b.totalTokens - a.totalTokens,
    ),
  );
  const bothMissing = $derived(!!summary && summary.sources.every((s) => s.status === "missing"));
  const pricingNote = $derived(
    !summary
      ? ""
      : summary.pricing.status === "unavailable"
        ? "Token counts only · pricing table unavailable"
        : "API-equivalent estimate · not subscription billing",
  );
  const showBody = $derived(!loading || !!summary);

  onMount(() => {
    void load(false);
  });

  async function load(force: boolean) {
    const gen = ++loadGen;
    loading = true;
    error = null;
    const window = makeWindow(windowDays);
    activeWindow = window;
    try {
      const next = await api.usageSummary({
        sinceDay: window.sinceDay,
        untilDay: window.untilDay,
        timeZone: window.timeZone,
        resolution: window.resolution,
        sinceTime: window.sinceTime,
        untilTime: window.untilTime,
        force,
      });
      if (gen !== loadGen) {
        return;
      }
      summary = next;
    } catch (err) {
      if (gen !== loadGen) {
        return;
      }
      error = displayError(parseInvokeError(err));
    } finally {
      if (gen === loadGen) {
        loading = false;
      }
    }
  }

  function setWindowDays(days: number) {
    windowDays = days;
    void load(false);
  }
</script>

<div class="flex flex-col gap-4 px-5 pt-[18px] pb-[26px]">
  <section class="rounded-[11px] border border-[var(--hair)] bg-[var(--plate)] p-3.5" aria-label="Usage controls">
    <div class="flex flex-wrap items-center gap-2">
      <div class="inline-grid grid-flow-col overflow-hidden rounded-lg border border-[var(--hair)]" role="group" aria-label="Window">
        {#each WINDOWS as option (option.days)}
          <button
            type="button"
            class="h-[30px] cursor-pointer rounded-none border-0 px-3 text-[11px] font-semibold tracking-[0.04em] uppercase focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--fill)] {windowDays ===
            option.days
              ? 'bg-[var(--fill)] text-[var(--fill-ink)]'
              : 'bg-[var(--plate)] text-[var(--mute)]'}"
            aria-pressed={windowDays === option.days}
            onclick={() => setWindowDays(option.days)}
          >
            {option.label}
          </button>
        {/each}
      </div>
      <div class="inline-grid grid-flow-col overflow-hidden rounded-lg border border-[var(--hair)]" role="group" aria-label="Metric">
        <button
          type="button"
          class="h-[30px] cursor-pointer rounded-none border-0 px-3 text-[11px] font-semibold tracking-[0.04em] uppercase focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--fill)] {metric ===
          'cost'
            ? 'bg-[var(--fill)] text-[var(--fill-ink)]'
            : 'bg-[var(--plate)] text-[var(--mute)]'}"
          aria-pressed={metric === "cost"}
          onclick={() => (metric = "cost")}
        >
          Cost
        </button>
        <button
          type="button"
          class="h-[30px] cursor-pointer rounded-none border-0 px-3 text-[11px] font-semibold tracking-[0.04em] uppercase focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--fill)] {metric ===
          'tokens'
            ? 'bg-[var(--fill)] text-[var(--fill-ink)]'
            : 'bg-[var(--plate)] text-[var(--mute)]'}"
          aria-pressed={metric === "tokens"}
          onclick={() => (metric = "tokens")}
        >
          Tokens
        </button>
      </div>
      <div class="flex-1"></div>
      <button
        type="button"
        class="flex h-[30px] items-center gap-1.5 rounded-lg border border-[var(--hair)] bg-[var(--well)] px-2.5 text-[11px] font-semibold tracking-[0.04em] uppercase focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--fill)] disabled:opacity-45"
        disabled={loading}
        onclick={() => void load(true)}
      >
        <RefreshCw class="size-3 {loading ? 'animate-spin' : ''}" aria-hidden="true" />
        Refresh
      </button>
    </div>
  </section>

  {#if loading && !summary}
    <p class="text-[13px] text-[var(--mute)]">Scanning transcripts…</p>
  {:else if error && !summary}
    <p class="text-[13px] text-[var(--trip)]">{error}</p>
  {:else if bothMissing}
    <p class="text-[13px] text-[var(--mute)]">No Claude or Codex session transcripts found on this machine.</p>
  {:else if showBody}
    {#if error}
      <p class="text-[13px] text-[var(--trip)]">{error}</p>
    {/if}
    <section class="rounded-[11px] border border-[var(--hair)] bg-[var(--plate)] p-4" aria-label="Usage totals">
      <div class="text-[10px] font-semibold tracking-[0.03em] text-[var(--mute)] uppercase">
        {metric === "cost" ? "Estimated cost" : "Processed tokens"}
      </div>
      <div class="mt-2 text-[34px] leading-none font-semibold">{headline}</div>
      <div class="mt-2.5 font-mono text-[11.5px] text-[var(--mute)]">
        {formatCount(folded.sessions)} sessions · {formatCount(folded.records)} records
        {#if folded.cacheSavingsUsd > 0 && metric === "cost"}
          · cache saved {formatUsd(folded.cacheSavingsUsd)}
        {/if}
        {#if loading}
          · scanning…
        {:else if summary?.cacheHit}
          · cached
        {/if}
      </div>
      <p class="mt-3 text-[11.5px] text-[var(--mute)]">{pricingNote}</p>
      {#if summary}
        <div class="mt-3 flex flex-wrap gap-2">
          {#each summary.sources as source (source.provider)}
            <span
              class="rounded border border-[var(--hair)] px-2 py-1 font-mono text-[10.5px] tracking-[0.03em] uppercase {source.status ===
              'ok'
                ? 'text-[var(--silkscreen)]'
                : 'text-[var(--mute)]'}"
            >
              {providerLabel(source.provider)}
              {#if source.status === "ok"}
                ok
              {:else if source.status === "missing"}
                missing
              {:else}
                {source.status}
              {/if}
            </span>
          {/each}
        </div>
      {/if}
    </section>

    <UsageChart
      {folded}
      {metric}
      sinceDay={activeWindow.sinceDay}
      untilDay={activeWindow.untilDay}
      sinceTime={activeWindow.sinceTime}
      untilTime={activeWindow.untilTime}
      hourly={windowDays === 1}
    />

    <section class="rounded-[11px] border border-[var(--hair)] bg-[var(--plate)]" aria-label="Models">
      <header class="border-b border-[var(--hair)] px-3 py-[9px] text-[11.5px] font-semibold tracking-[0.03em] uppercase">
        Models
      </header>
      {#if models.length === 0}
        <p class="px-3 py-3 text-[13px] text-[var(--mute)]">No model activity in this window.</p>
      {:else}
        {#each models as row (row.provider + row.model)}
          <div class="flex items-center gap-3 border-b border-[var(--hair)] px-3 py-2.5 last:border-b-0">
            <span class="w-[52px] shrink-0 text-[10px] font-semibold tracking-[0.04em] text-[var(--mute)] uppercase"
              >{providerLabel(row.provider)}</span
            >
            <span class="min-w-0 flex-1 truncate text-[14px] font-semibold leading-none">{row.model}</span>
            <span class="font-mono text-[12px] text-[var(--mute)]"
              >{formatPercent(metric === "cost" ? row.costShare : row.tokenShare)}</span
            >
            <span class="font-mono w-[88px] text-right text-[13px] font-medium">
              {metric === "cost" ? formatUsd(row.costUsd) : formatTokens(row.totalTokens)}
            </span>
          </div>
        {/each}
      {/if}
    </section>

    <section class="rounded-[11px] border border-[var(--hair)] bg-[var(--plate)]" aria-label="Recent periods">
      <header class="border-b border-[var(--hair)] px-3 py-[9px] text-[11.5px] font-semibold tracking-[0.03em] uppercase">
        Recent
      </header>
      {#if recent.length === 0}
        <p class="px-3 py-3 text-[13px] text-[var(--mute)]">No activity in this window.</p>
      {:else}
        {#each recent as period (period.hourStart ?? period.day)}
          <div class="flex items-center gap-3 border-b border-[var(--hair)] px-3 py-2.5 last:border-b-0">
            <span class="min-w-[88px] font-mono text-[12px] text-[var(--mute)]">
              {period.hourStart
                ? new Date(period.hourStart).toLocaleString(undefined, {
                    month: "short",
                    day: "numeric",
                    hour: "numeric",
                  })
                : formatDayShort(period.day)}
            </span>
            <div class="flex-1"></div>
            <span class="font-mono text-[13px] font-medium">
              {metric === "cost" ? formatUsd(period.costUsd) : formatTokens(period.totalTokens)}
            </span>
          </div>
        {/each}
      {/if}
    </section>
  {/if}
</div>

// ui/src/features/usage/Usage.tsx
import { useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { RefreshCw } from "lucide-react";
import * as api from "$lib/api";
import { displayError, parseInvokeError } from "$lib/error";
import { PROVIDERS, foldUsage, providerLabel } from "$lib/usageMerge";
import {
  formatCount,
  formatDayRange,
  formatDayShort,
  formatPercent,
  formatTokens,
  formatUsd,
  makeWindow,
} from "$lib/usageFormat";
import type { UsageMetric } from "$lib/usageTypes";
import type { AgentId } from "$lib/types";
import { ProviderIcon } from "$lib/ProviderIcon";
import { UsageChart } from "./UsageChart";

const WINDOWS = [
  { days: 1, label: "Past 24h" },
  { days: 7, label: "7 days" },
  { days: 30, label: "30 days" },
  { days: 90, label: "90 days" },
] as const;

type BreakdownMode = "model" | "day";

const PROVIDER_DOT: Record<AgentId, string> = {
  codex: "var(--silkscreen)",
  claude: "#e8944a",
  antigravity: "var(--mute)",
};

function Segmented<T extends string>({
  value,
  options,
  ariaLabel,
  onChange,
}: {
  value: T;
  options: readonly { value: T; label: string }[];
  ariaLabel: string;
  onChange: (value: T) => void;
}) {
  return (
    <div
      className="inline-grid grid-flow-col overflow-hidden rounded-md border border-[var(--hair)]"
      role="group"
      aria-label={ariaLabel}
    >
      {options.map((option) => (
        <button
          key={option.value}
          type="button"
          className={`h-7 cursor-pointer rounded-none border-0 px-2.5 text-[10.5px] font-semibold tracking-[0.05em] uppercase focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--fill)] ${
            value === option.value
              ? "bg-[var(--fill)] text-[var(--fill-ink)]"
              : "bg-transparent text-[var(--mute)]"
          }`}
          aria-pressed={value === option.value}
          onClick={() => onChange(option.value)}
        >
          {option.label}
        </button>
      ))}
    </div>
  );
}

export function Usage() {
  const [windowDays, setWindowDays] = useState(30);
  const [metric, setMetric] = useState<UsageMetric>("cost");
  const [breakdown, setBreakdown] = useState<BreakdownMode>("model");
  const [forceRevision, setForceRevision] = useState(0);
  const forceRef = useRef(false);
  const activeWindow = makeWindow(windowDays);

  const query = useQuery({
    queryKey: ["usage", windowDays, forceRevision],
    queryFn: async () => {
      const window = makeWindow(windowDays);
      const force = forceRef.current;
      forceRef.current = false;
      return api.usageSummary({
        sinceDay: window.sinceDay,
        untilDay: window.untilDay,
        timeZone: window.timeZone,
        resolution: window.resolution,
        sinceTime: window.sinceTime,
        untilTime: window.untilTime,
        force,
      });
    },
  });

  const summary = query.data ?? null;
  const loading = query.isFetching;
  const error = query.error ? displayError(parseInvokeError(query.error), "Usage") : null;
  const folded = foldUsage(summary);
  const bothMissing = !!summary && summary.sources.every((s) => s.status === "missing");
  const showBody = !loading || !!summary;

  const inputTokens =
    folded.tokens.uncachedInputTokens + folded.tokens.cachedInputTokens + folded.tokens.cacheCreationTokens;
  const cachedShare = inputTokens === 0 ? 0 : folded.tokens.cachedInputTokens / inputTokens;
  const tokensPerActiveDay = folded.activeDays === 0 ? 0 : folded.totalTokens / folded.activeDays;
  const cacheMultiple = folded.costUsd > 0 ? folded.cacheSavingsUsd / folded.costUsd : 0;

  const providers = PROVIDERS.map((provider) => {
    const row = folded.providers.find((item) => item.provider === provider);
    return (
      row ?? {
        provider,
        costUsd: 0,
        totalTokens: 0,
        records: 0,
        costShare: 0,
        tokenShare: 0,
      }
    );
  }).sort((a, b) => b.costUsd - a.costUsd || b.totalTokens - a.totalTokens);

  const models = [...folded.models].sort((a, b) =>
    metric === "cost" ? b.costUsd - a.costUsd : b.totalTokens - a.totalTokens,
  );

  const days = [...folded.daily]
    .filter((period) => period.costUsd > 0 || period.totalTokens > 0)
    .sort((a, b) =>
      metric === "cost" ? b.costUsd - a.costUsd : b.totalTokens - a.totalTokens,
    );

  const pricingNote = !summary
    ? ""
    : summary.pricing.status === "unavailable"
      ? "Token counts only · pricing table unavailable"
      : "if billed at full API rate";

  function refresh() {
    forceRef.current = true;
    setForceRevision((n) => n + 1);
  }

  return (
    <div className="flex flex-col gap-7 px-5 pt-[18px] pb-[28px]">
      <header className="flex flex-wrap items-center gap-3">
        <div className="min-w-0 flex-1 font-mono text-[12px] text-[var(--mute)]">
          {formatDayRange(activeWindow.sinceDay, activeWindow.untilDay)}
          {loading ? <span className="ml-2">· scanning…</span> : null}
          {!loading && summary?.cacheHit ? <span className="ml-2">· cached</span> : null}
        </div>
        <Segmented
          ariaLabel="Window"
          value={String(windowDays)}
          options={WINDOWS.map((option) => ({ value: String(option.days), label: option.label }))}
          onChange={(value) => setWindowDays(Number(value))}
        />
        <button
          type="button"
          className="inline-flex size-7 items-center justify-center rounded-md border border-[var(--hair)] bg-transparent text-[var(--mute)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--fill)] disabled:opacity-45"
          disabled={loading}
          aria-label="Refresh usage"
          onClick={refresh}
        >
          <RefreshCw className={`size-3.5 ${loading ? "animate-spin" : ""}`} aria-hidden="true" />
        </button>
      </header>

      {loading && !summary ? (
        <p className="text-[13px] text-[var(--mute)]">Scanning transcripts…</p>
      ) : error && !summary ? (
        <p className="text-[13px] text-[var(--trip)]">{error}</p>
      ) : bothMissing ? (
        <p className="text-[13px] text-[var(--mute)]">No Claude or Codex session transcripts found on this machine.</p>
      ) : showBody ? (
        <>
          {error ? <p className="text-[13px] text-[var(--trip)]">{error}</p> : null}

          <section aria-label="Usage totals">
            <div className="text-[11px] font-semibold tracking-[0.06em] text-[var(--mute)] uppercase">
              {metric === "cost" ? "Raw token cost" : "Processed tokens"}
            </div>
            <div className="mt-1.5 text-[40px] leading-none font-semibold tracking-[-0.03em]">
              {metric === "cost" ? formatUsd(folded.costUsd) : formatTokens(folded.totalTokens)}
            </div>
            <p className="mt-2 text-[12px] text-[var(--mute)]">{pricingNote}</p>

            <div className="mt-5 flex flex-col gap-3.5">
              {providers.map((row) => {
                const share = metric === "cost" ? row.costShare : row.tokenShare;
                return (
                  <div key={row.provider} className="grid gap-1.5">
                    <div className="flex items-center gap-2">
                      <ProviderIcon provider={row.provider} className="size-3.5 shrink-0" />
                      <span className="text-[13px] font-semibold">{providerLabel(row.provider)}</span>
                      <span className="font-mono text-[13px] font-medium">
                        {metric === "cost" ? formatUsd(row.costUsd) : formatTokens(row.totalTokens)}
                      </span>
                      <span className="font-mono text-[11.5px] text-[var(--mute)]">
                        {formatPercent(share)} of {metric}
                        {" · "}
                        {formatTokens(row.totalTokens)} tokens
                      </span>
                    </div>
                    <div className="h-[3px] overflow-hidden rounded-full bg-[var(--well)]">
                      <div
                        className="h-full rounded-full"
                        style={{
                          width: `${Math.max(0, Math.min(100, share * 100))}%`,
                          background: PROVIDER_DOT[row.provider],
                        }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </section>

          <UsageChart
            folded={folded}
            metric={metric}
            onMetricChange={setMetric}
            sinceDay={activeWindow.sinceDay}
            untilDay={activeWindow.untilDay}
            sinceTime={activeWindow.sinceTime}
            untilTime={activeWindow.untilTime}
            hourly={windowDays === 1}
          />

          <section
            className="grid gap-4 border-y border-[var(--hair)] py-4 sm:grid-cols-2 lg:grid-cols-5"
            aria-label="Token metrics"
          >
            <Metric
              label="Processed tokens"
              value={formatTokens(folded.totalTokens)}
              hint={
                folded.activeDays > 0
                  ? `${formatTokens(tokensPerActiveDay)} per active day`
                  : `${formatCount(folded.sessions)} sessions`
              }
            />
            <Metric
              label="Cached input"
              value={formatTokens(folded.tokens.cachedInputTokens)}
              hint={`${formatPercent(cachedShare)} of observed input`}
            />
            <Metric
              label="Uncached input"
              value={formatTokens(folded.tokens.uncachedInputTokens)}
              hint={`${formatTokens(folded.tokens.cacheCreationTokens)} cache writes`}
            />
            <Metric
              label="Output"
              value={formatTokens(folded.tokens.outputTokens)}
              hint={
                folded.tokens.reasoningTokens > 0
                  ? `includes ${formatTokens(folded.tokens.reasoningTokens)} reasoning`
                  : `${formatCount(folded.records)} records`
              }
            />
            <Metric
              label="Cache savings"
              value={formatUsd(folded.cacheSavingsUsd)}
              hint={cacheMultiple > 0 ? `${cacheMultiple.toFixed(1)}x the raw token cost` : "vs full API rate"}
            />
          </section>

          <section aria-label="Breakdown">
            <div className="mb-3 flex items-center gap-3">
              <span className="text-[13px] font-semibold tracking-[-0.01em]">Breakdown</span>
              <div className="flex-1" />
              <Segmented
                ariaLabel="Breakdown"
                value={breakdown}
                options={[
                  { value: "model", label: "Model" },
                  { value: "day", label: "Day" },
                ]}
                onChange={setBreakdown}
              />
            </div>

            <div className="grid grid-cols-[minmax(0,1.4fr)_88px_64px_88px] gap-2 border-b border-[var(--hair)] pb-2 font-mono text-[10.5px] tracking-[0.04em] text-[var(--mute)] uppercase">
              <span>{breakdown === "model" ? "Model" : "Day"}</span>
              <span className="text-right">Cost</span>
              <span className="text-right">Share</span>
              <span className="text-right">Tokens</span>
            </div>

            {breakdown === "model" ? (
              models.length === 0 ? (
                <p className="py-4 text-[13px] text-[var(--mute)]">No model activity in this window.</p>
              ) : (
                models.map((row) => (
                  <div
                    key={`${row.provider}-${row.model}`}
                    className="grid grid-cols-[minmax(0,1.4fr)_88px_64px_88px] items-center gap-2 border-b border-[var(--hair)] py-2.5 last:border-b-0"
                  >
                    <div className="flex min-w-0 items-center gap-2">
                      <ProviderIcon provider={row.provider} className="size-3.5 shrink-0" />
                      <span className="truncate text-[13.5px] font-medium">{row.model}</span>
                    </div>
                    <span className="font-mono text-right text-[12.5px]">{formatUsd(row.costUsd)}</span>
                    <span className="font-mono text-right text-[12px] text-[var(--mute)]">
                      {formatPercent(metric === "cost" ? row.costShare : row.tokenShare)}
                    </span>
                    <span className="font-mono text-right text-[12.5px]">{formatTokens(row.totalTokens)}</span>
                  </div>
                ))
              )
            ) : days.length === 0 ? (
              <p className="py-4 text-[13px] text-[var(--mute)]">No activity in this window.</p>
            ) : (
              days.map((period) => {
                const share =
                  metric === "cost"
                    ? folded.costUsd === 0
                      ? 0
                      : period.costUsd / folded.costUsd
                    : folded.totalTokens === 0
                      ? 0
                      : period.totalTokens / folded.totalTokens;
                return (
                  <div
                    key={period.day}
                    className="grid grid-cols-[minmax(0,1.4fr)_88px_64px_88px] items-center gap-2 border-b border-[var(--hair)] py-2.5 last:border-b-0"
                  >
                    <span className="font-mono text-[13px]">{formatDayShort(period.day)}</span>
                    <span className="font-mono text-right text-[12.5px]">{formatUsd(period.costUsd)}</span>
                    <span className="font-mono text-right text-[12px] text-[var(--mute)]">{formatPercent(share)}</span>
                    <span className="font-mono text-right text-[12.5px]">{formatTokens(period.totalTokens)}</span>
                  </div>
                );
              })
            )}
          </section>
        </>
      ) : null}
    </div>
  );
}

function Metric({ label, value, hint }: { label: string; value: string; hint: string }) {
  return (
    <div className="min-w-0">
      <div className="text-[10.5px] font-semibold tracking-[0.05em] text-[var(--mute)] uppercase">{label}</div>
      <div className="mt-1 text-[18px] leading-none font-semibold tracking-[-0.02em]">{value}</div>
      <div className="mt-1.5 text-[11.5px] text-[var(--mute)]">{hint}</div>
    </div>
  );
}
